#!/usr/bin/env bash
# Open a clean Neovim with ONLY plurnk.nvim installed, against the daemon
# at $PLURNK_HOST:$PLURNK_PORT (default 127.0.0.1:3044). Isolated XDG
# directories so your global config / cache / state stay untouched.
#
# Usage:
#   ./demo.sh                                  — defaults
#   PLURNK_PORT=3045 ./demo.sh                 — custom port
#   PLURNK_HOST=10.0.0.1 ./demo.sh             — remote daemon
#   ./demo.sh path/to/file.txt                 — open with a file
set -euo pipefail

PLURNK_HOST="${PLURNK_HOST:-127.0.0.1}"
PLURNK_PORT="${PLURNK_PORT:-3044}"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
DEMO_ROOT="${PLURNK_DEMO_HOME:-/tmp/plurnk-nvim-demo}"

export XDG_CONFIG_HOME="$DEMO_ROOT/config"
export XDG_DATA_HOME="$DEMO_ROOT/data"
export XDG_STATE_HOME="$DEMO_ROOT/state"
export XDG_CACHE_HOME="$DEMO_ROOT/cache"

mkdir -p "$XDG_CONFIG_HOME/nvim"

INIT="$XDG_CONFIG_HOME/nvim/init.lua"
cat > "$INIT" <<EOF
-- Generated by plurnk.nvim/demo.sh. Anything you put in $XDG_CONFIG_HOME
-- is wiped on the next demo.sh run.

vim.opt.termguicolors = true
vim.opt.number = true
vim.opt.signcolumn = "yes"

-- Load plurnk.nvim from the source tree.
vim.opt.rtp:prepend("$REPO_DIR")

require("plurnk").setup({
  host = "$PLURNK_HOST",
  port = $PLURNK_PORT,
})
require("plurnk").apply_default_keymaps()

vim.opt.statusline = "%f %h%w%m%r %=%{v:lua.require('plurnk').statusline()} %y %l/%L"

-- Print a banner so the demo user sees what we connected to.
vim.schedule(function()
  vim.cmd("echom 'plurnk.nvim demo · ws://$PLURNK_HOST:$PLURNK_PORT · :PlurnkPing to verify'")
end)
EOF

echo "demo XDG: $DEMO_ROOT"
echo "daemon:   ws://$PLURNK_HOST:$PLURNK_PORT"
echo "starting nvim..."
echo

exec nvim "$@"
